spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: devstoreaccount1
          container-name: blobcontainer
          account-key: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
          endpoint: http://127.0.0.1:10000/devstoreaccount1
